# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [17]:
a= np.zeros(10)


3. Create a vector with values ranging from 10 to 49

In [4]:
b=np.arange(10,49)


4. Find the shape of previous array in question 3

In [21]:
np.shape(b)

(39,)

5. Print the type of the previous array in question 3

In [5]:
print(b.dtype)

int32


6. Print the numpy version and the configuration


In [6]:
print(np._version_)
print(np.show_conig())

AttributeError: module 'numpy' has no attribute '_version_'

7. Print the dimension of the array in question 3


In [25]:
b.ndim

1

8. Create a boolean array with all the True values

In [7]:
boolean=np.ones((2,2), dtype=bool)


array([[ True,  True],
       [ True,  True]])

9. Create a two dimensional array




In [33]:
array2d = np.array([[1,2,3], [1,2,3]])

10. Create a three dimensional array



In [36]:
array3d = np.array([[[1,2,3], [1,2,3],[1,2,3]]])


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [38]:
c=np.array([1,2,3])
c=c[::-1]


array([3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [41]:
d=np.zeros(10)
d[4]=1

13. Create a 3x3 identity matrix

In [42]:
e=np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [48]:
arr = np.array([1, 2, 3, 4, 5])
f_arr = arr.astype(np.float64)


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [8]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
np.multiply(arr1,arr2)


array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [10]:
arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])
arr3=(arr1==arr2)
arr3

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [5]:
odd= np.arange(10)
odd[odd % 2 == 1]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [9]:
odd[odd % 2 == 1]=-1

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [15]:
arr = np.arange(10)
arr[5:9]=12

20. Create a 2d array with 1 on the border and 0 inside

In [14]:
inside0 = np.ones((3,3))
inside0[1:-1,1:-1] = 0
inside0


array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [19]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [21]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [26]:
slicing=np.arange(10).reshape(5,2)
slicing[0]


array([0, 1])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [40]:
slice2nd=np.arange(10).reshape(2,5)
slice2nd[1,1:2]

array([6])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [42]:
slice3rdcol=np.arange(10).reshape(2,5)
slice3rdcol[0:, 2:3]

array([[2],
       [7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [43]:
minmax=np.random.rand(10,10)
minmax

array([[0.19018678, 0.81202888, 0.005773  , 0.57096841, 0.68404075,
        0.97292939, 0.03749491, 0.9657023 , 0.5256324 , 0.21566626],
       [0.762959  , 0.14167269, 0.61172397, 0.57300921, 0.71236667,
        0.64241167, 0.72288774, 0.37314708, 0.18806327, 0.24545795],
       [0.17890624, 0.9817771 , 0.69541909, 0.62913233, 0.46315855,
        0.79358634, 0.21202619, 0.72294058, 0.47737129, 0.97055662],
       [0.87780891, 0.54775213, 0.97295496, 0.83690955, 0.89934605,
        0.49889522, 0.79478062, 0.34336342, 0.96929142, 0.63508718],
       [0.64864904, 0.17385842, 0.52120623, 0.73064657, 0.20337215,
        0.03151983, 0.19618677, 0.9221952 , 0.60564188, 0.82290944],
       [0.27903721, 0.10773384, 0.73807841, 0.92085426, 0.04626945,
        0.77960075, 0.58628717, 0.8587577 , 0.32847465, 0.04006225],
       [0.23801408, 0.24422063, 0.06235157, 0.63269056, 0.79235808,
        0.59866824, 0.79670784, 0.08802268, 0.30301234, 0.2611544 ],
       [0.66866771, 0.22460372, 0.9028406

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [48]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
a[a==b]

array([2, 2, 4, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [9]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np. where(a == b)


(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [9]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!='will']

array([[-0.2642949 ,  0.1245275 ,  0.18975551,  0.18410198],
       [-1.24589988,  0.25796818, -1.44646337,  1.3989486 ],
       [ 1.54139811, -0.67572918, -0.05968958, -0.43632111],
       [ 0.16215239,  0.98459896,  0.01805001, -1.70455562],
       [-0.73616279,  0.31933247,  0.53513649,  0.37237063],
       [ 0.41198839,  1.34278439,  1.9522066 ,  0.37008099],
       [-0.45109955,  0.03530735, -2.47844764,  0.16198688]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [51]:
x=np.arange(1,16).reshape(5,3)

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [58]:
y=np.arange(1,17).reshape(2,2,4)
y

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [62]:
np.swapaxes(y,2,1)

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [63]:
simplearray=np.random.rand(10)
sqroot=np.sqrt(simplearray)
sqroot[sqroot<0.5]=0


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [69]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unames=np.unique(names)
unames=np.sort(unames)
unames

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [72]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([6, 7, 8, 9])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [77]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
dlt=np.delete(sampleArray, 0,1)
insertarr=np.insert(dlt,1,newColumn,axis=1)

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [78]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum